export type SolarTermDetail = {
  name: string;
  intro: string;
  meaning: string;
  climate: string;
  origin: string;
  food: string;
  customs: string;
  health: string;
};

export const SOLAR_TERM_DETAILS: Record<string, SolarTermDetail> = {
  '立春': {
    name: 'Beginning of Spring(Li Chun)',
    intro: 'The first solar term of the year, usually falling around February 3-5. It marks the beginning of spring in the traditional calendar, when nature starts to wake after winter.',
    meaning: 'Renewal, growth, and a fresh yearly cycle',
    climate: 'Cold air may still return, but temperatures begin to rise and early signs of spring appear.',
    origin: 'Start of Spring has been observed since ancient times as an important seasonal marker for farming and spring welcoming rituals.',
    food: 'Spring pancakes, spring rolls, radish, chives, bean sprouts, and other fresh foods that symbolize the arrival of spring.',
    customs: 'Welcoming spring, biting spring foods, honoring the spring deity, and symbolic spring ox ceremonies.',
    health: 'Protect yang energy, keep warm during sudden cold spells, sleep early, rise early, and choose light, fresh foods.',
  },
  '雨水': {
    name: 'Rain Water(Yu Shui)',
    intro: 'Rain Water usually arrives around February 18-20. It signals warming weather, melting snow, and gradually increasing rainfall.',
    meaning: 'Moisture returns and nourishes all living things',
    climate: 'Temperatures rise slowly, rainfall increases, and late cold waves may still occur.',
    origin: 'The term reflects the transition from snow to rain in many northern regions and became an important farming signal.',
    food: 'Honey, dates, Chinese yam, lotus seeds, and mildly sweet foods that support digestion.',
    customs: 'In some regions, families visit relatives and hold blessings for children during this period.',
    health: 'Care for the spleen and stomach, avoid removing warm clothing too early, and keep meals gentle and balanced.',
  },
  '惊蛰': {
    name: 'Awakening of Insects(Jing Zhe)',
    intro: 'Awakening of Insects usually falls around March 5-7. Spring thunder was believed to wake hibernating creatures, bringing visible vitality back to nature.',
    meaning: 'Thunder stirs life and hidden creatures awaken',
    climate: 'Weather warms quickly, rain becomes more frequent, and spring thunder may begin.',
    origin: 'The ancient name was later changed to Awakening of Insects. Classical calendars describe this period as the time when insects emerge after thunder.',
    food: 'Pears are a common seasonal food; light vegetables such as bamboo shoots, spinach, celery, and yam are also suitable.',
    customs: 'Eating pears, symbolic rituals to drive away bad luck, and local customs related to thunder and protection.',
    health: 'Support the liver, keep meals light, rise early, and increase gentle outdoor activity.',
  },
  '春分': {
    name: 'Spring Equinox(Chun Fen)',
    intro: 'Spring Equinox usually falls around March 20-22, when day and night are nearly equal in length.',
    meaning: 'Balance of day and night, yin and yang',
    climate: 'Weather becomes mild and bright, while severe cold waves are less common.',
    origin: 'It is one of the earliest solar terms to be identified through ancient shadow measurement.',
    food: 'Fresh seasonal greens such as shepherds purse, toon shoots, bamboo shoots, and spinach.',
    customs: 'Balancing eggs, flying kites, spring worship, and sharing symbolic spring ox images.',
    health: 'Maintain balance, eat moderately, avoid extremes of hot or cold foods, and spend time outdoors.',
  },
  '清明': {
    name: 'Pure Brightness(Qing Ming)',
    intro: 'Pure Brightness usually falls around April 4-6. It is both a solar term and a traditional festival for remembrance and spring outings.',
    meaning: 'Clear skies, bright scenery, and renewed life',
    climate: 'Temperatures rise, rain increases, and plants grow vigorously.',
    origin: 'Pure Brightness gradually merged with older spring festivals and became closely tied to ancestor remembrance.',
    food: 'Qingtuan, cold-food festival snacks, and seasonal wild greens.',
    customs: 'Tomb sweeping, spring outings, willow customs, kite flying, swings, and traditional games.',
    health: 'Soothe the liver, support digestion, protect against wind, and keep a steady mood.',
  },
  '谷雨': {
    name: 'Grain Rain(Gu Yu)',
    intro: 'Grain Rain usually arrives around April 19-21 and is the last solar term of spring. Its name means rain that helps grains grow.',
    meaning: 'Rain nourishes crops and supports growth',
    climate: 'Rainfall and humidity increase, and temperatures continue to rise.',
    origin: 'The name comes from the farming idea that spring rain brings grain growth, with legends also linking it to the invention of writing.',
    food: 'Toon shoots, Grain Rain tea, barley, yam, red beans, and foods that help dispel dampness.',
    customs: 'Drinking Grain Rain tea, admiring peonies, eating toon shoots, and honoring Cangjie in some regions.',
    health: 'Focus on clearing dampness, supporting digestion, and choosing simple meals.',
  },
  '立夏': {
    name: 'Start of Summer(Li Xia)',
    intro: 'Start of Summer usually falls around May 5-7 and marks the beginning of summer in the traditional calendar.',
    meaning: 'Summer begins and living things flourish',
    climate: 'Heat gradually increases, thunderstorms become more common, and plants grow rapidly.',
    origin: 'Ancient courts held summer welcoming ceremonies to pray for seasonal prosperity.',
    food: 'Seasonal fresh foods, Start of Summer rice, eggs, duck eggs, vegetables, and fruit.',
    customs: 'Weighing people, egg games, eating Start of Summer eggs, and sharing seasonal tea.',
    health: 'Protect the heart, prevent heat and dampness, rest at noon when needed, and eat lightly.',
  },
  '小满': {
    name: 'Lesser Fullness of Grain(Xiao Man)',
    intro: 'Lesser Fullness of Grain usually falls around May 20-22. Summer crops begin to fill with grain but are not fully mature.',
    meaning: 'Grain begins to fill, but fullness is not yet complete',
    climate: 'Rain increases, humidity rises, and the weather becomes muggy.',
    origin: 'Classical calendars describe this period as the time when things become slightly full.',
    food: 'Winter melon, bitter melon, coix seed, mung beans, and other foods that clear heat and dampness.',
    customs: 'Honoring water wheels, silkworm rituals, and farming customs around water, oil, and silk work.',
    health: 'Clear heat, reduce dampness, ventilate rooms, and exercise moderately to release sweat.',
  },
  '芒种': {
    name: 'Grain in Beard(Mang Zhong)',
    intro: 'Grain in Beard usually falls around June 5-7. It is a busy farming period for harvesting awned crops and sowing summer grains.',
    meaning: 'Awned grains ripen and summer sowing begins',
    climate: 'Temperatures rise, rainfall is abundant, and hot humid weather becomes common.',
    origin: 'Traditional communities held flower farewell rituals and farming ceremonies during this busy period.',
    food: 'Light meals, green plums, and foods that relieve heat while supporting energy.',
    customs: 'Boiling green plums, farewell-to-flower rituals, seedling ceremonies, and local harvest customs.',
    health: 'Clear summer heat, support the heart and spleen, nap when needed, and avoid greasy spicy food.',
  },
  '夏至': {
    name: 'Summer Solstice(Xia Zhi)',
    intro: 'Summer Solstice usually falls around June 21-22. It is the longest day and shortest night of the year in the Northern Hemisphere.',
    meaning: 'Daylight reaches its peak and yin begins to return',
    climate: 'Heat, heavy rain, and humid weather are common.',
    origin: 'It is one of the earliest established solar terms and had official rituals in ancient times.',
    food: 'Noodles are common in northern customs; light foods, bitter flavors, and moderate ginger are also traditional.',
    customs: 'Ancestor rites, cooling summer customs, eating solstice noodles, and exchanging fans or summer gifts.',
    health: 'Prevent heatstroke, hydrate well, avoid excessive cold foods, and keep exercise moderate.',
  },
  '小暑': {
    name: 'Lesser Heat(Xiao Shu)',
    intro: 'Lesser Heat usually arrives around July 6-8. Heat is building and the hottest dog days are near.',
    meaning: 'Heat begins to intensify',
    climate: 'Hot days, thunderstorms, and frequent rain are common.',
    origin: 'Classical calendars describe Minor Heat as heat that has arrived but has not yet reached its peak.',
    food: 'Light, cooling foods; dumplings in some northern customs, lotus root and new grain in some southern regions.',
    customs: 'Tasting new grain, drying books and clothes, summer leisure customs, and cricket activities.',
    health: 'Clear heat, calm the mind, prevent heatstroke, and avoid overusing cold drinks or air conditioning.',
  },
  '大暑': {
    name: 'Greater Heat (Da Shu)',
    intro: 'Greater Heat  usually falls around July 22-24 and is often the hottest period of the year.',
    meaning: 'Extreme heat and heavy dampness',
    climate: 'High heat, thunderstorms, humidity, and typhoons in some regions.',
    origin: 'It occurs around the middle of the dog days and represents peak summer heat.',
    food: 'Cooling and nutritious foods, herbal tea, grass jelly, ginger prepared in summer, and regional summer soups.',
    customs: 'Sending off the Major Heat boat, drinking summer tea, eating litchi in some regions, and drying ginger.',
    health: 'Avoid intense heat, drink enough water, clear internal heat, and guard against dampness.',
  },
  '立秋': {
    name: 'Start of Autumn(Li Qiu)',
    intro: 'Start of Autumn usually falls around August 7-9. It marks the beginning of autumn, though summer heat may continue.',
    meaning: 'Autumn begins and heat slowly recedes',
    climate: 'Heat gradually eases, day-night temperature differences increase, and rainfall decreases.',
    origin: 'Ancient ceremonies welcomed autumn in the west, following seasonal ritual directions.',
    food: 'Autumn tonic foods, porridge, and nourishing but not overly heavy meals.',
    customs: 'Autumn nourishing customs, biting autumn foods, sun-drying harvests, and harvest gatherings.',
    health: 'Nourish yin, prevent dryness, protect the lungs, sleep early, and reduce overly spicy foods.',
  },
  '处暑': {
    name: 'End of Heat(Chu Shu)',
    intro: 'End of Heat usually falls around August 22-24. The character means stopping, signaling that summer heat begins to fade.',
    meaning: 'Heat withdraws and autumn coolness approaches',
    climate: 'Temperatures drop, skies clear, and day-night differences grow.',
    origin: 'Classical calendars explain it as the point when summer heat comes to an end.',
    food: 'Duck, lotus root, white fungus, pears, and foods that nourish yin and moisten dryness.',
    customs: 'Welcoming autumn, river lanterns, fishing festivals, autumn outings, and eating duck.',
    health: 'Prevent autumn dryness, nourish the lungs, keep a regular schedule, and avoid dressing too warmly too soon.',
  },
  '白露': {
    name: 'White Dew(Bai Lu)',
    intro: 'Bai Lu usually falls around September 7-9. Cooler nights create visible dew, which gives the term its name.',
    meaning: 'Cool air condenses dew into white drops',
    climate: 'Large day-night temperature differences, cooler mornings, and obvious autumn dryness.',
    origin: 'Ancient explanations connect Bai Lu with autumn metal energy and cooling moisture.',
    food: 'Longan, sweet potato, Bai Lu tea, rice wine, pears, lily bulbs, and white fungus.',
    customs: 'Collecting clear dew, drinking Bai Lu tea, brewing rice wine, and regional water-deity rituals.',
    health: 'Add clothing morning and evening, moisturize the lungs and skin, and eat foods that ease dryness.',
  },
  '秋分': {
    name: 'the Autumn Equinox(Qiu Fen)',
    intro: ' the Autumn Equinox usually falls around September 22-24, when day and night are nearly equal worldwide.',
    meaning: 'Day and night are balanced, and autumn is halfway through',
    climate: 'Clear autumn air, less rain, dryness, and falling temperatures.',
    origin: 'It was identified through ancient shadow measurement and is linked to moon worship traditions.',
    food: 'Foods that nourish yin and moisten the lungs, such as yam, gorgon fruit, and poria.',
    customs: 'Moon worship, eating autumn greens, sending autumn ox pictures, and balancing eggs.',
    health: 'Seek gentle balance, moisturize dryness, sleep early, and avoid overly drying foods.',
  },
  '寒露': {
    name: 'Cold Dew(Han Lu)',
    intro: 'Cold Dew usually falls around October 7-9 and marks the transition from cool autumn to colder weather.',
    meaning: 'Dew turns colder and chill deepens',
    climate: 'Temperatures drop sharply, dew feels cold, and autumn deepens.',
    origin: 'Classical calendars describe dew at this time as cold and close to condensing.',
    food: 'Warm and moist foods, crabs in some regions, Han Lu tea, chrysanthemum dishes, and cakes.',
    customs: 'Climbing high places, admiring chrysanthemums, drinking chrysanthemum wine, eating flower cakes, and autumn fishing.',
    health: 'Keep feet warm, protect against cold, and balance warming foods with moisture-preserving foods.',
  },
  '霜降': {
    name: 'Frost Descent(Shuang jiang)',
    intro: 'Frost\'s Descent usually falls around October 23-24. It is the last solar term of autumn, when frost may begin to appear.',
    meaning: 'Cold air condenses and frost begins',
    climate: 'Temperatures drop quickly, mornings may bring frost, and dryness remains strong.',
    origin: 'Classical calendars describe the air becoming solemn and condensing dew into frost.',
    food: 'Persimmons, mutton hotpot in the north, duck in the south, and moderate seasonal tonics.',
    customs: 'Eating persimmons, admiring chrysanthemums, climbing high places, and regional Frost Descent festivals.',
    health: 'Warm the body, moisten dryness, protect the lungs, and prevent respiratory discomfort.',
  },
  '立冬': {
    name: 'Start of Winter(Li Dong)',
    intro: 'Start of Winter usually falls around November 7-8. It marks the beginning of winter and the season of storage.',
    meaning: 'Winter begins and life enters storage',
    climate: 'Temperatures drop, cold winds increase, and weather becomes drier.',
    origin: 'Ancient rulers welcomed winter in formal rituals, and many regions kept winter nourishing customs.',
    food: 'Dumplings in the north; chicken, duck, fish, sesame oil chicken, and ginger duck in some southern regions.',
    customs: 'Winter tonics, eating dumplings, welcoming winter, winter greetings, and winter swimming in some areas.',
    health: 'Preserve energy, sleep earlier and rise later, keep warm, and choose nourishing warm foods.',
  },
  '小雪': {
    name: 'Lesser Snow(Xiao Xue)',
    intro: 'Lesser Snow usually falls around November 22-23. It signals the beginning of snowfall, though snow is generally light.',
    meaning: 'Snow begins and cold strengthens',
    climate: 'Temperatures continue to fall, snow may begin, and the air becomes cold and dry.',
    origin: 'Classical calendars describe rain meeting cold air and turning into snow, with the amount still small.',
    food: 'Mutton, beef, walnuts, dates, glutinous rice cakes, preserved meat, and other warming foods.',
    customs: 'Curing preserved meat, eating glutinous rice cakes, drying fish, and making Minor Snow wine.',
    health: 'Warm and support yang energy, protect against cold, and keep moderate movement.',
  },
  '大雪': {
    name: 'Greater Snow(Da Xue)',
    intro: 'Greater Snow usually falls around December 6-8. Snowfall becomes more likely and heavier than during Lesser Snow.',
    meaning: 'Snow increases and deep winter approaches',
    climate: 'Temperatures drop clearly, snow increases, and freezing weather may appear.',
    origin: 'Classical calendars describe this as the time when snow becomes abundant.',
    food: 'Mutton, beef, dates, longan, red date cakes, and warming foods that support yang.',
    customs: 'Curing preserved meat, enjoying frozen rivers, winter tonics, and ice activities.',
    health: 'Keep warm, protect the kidneys, sleep early, rise later, and avoid unnecessary cold exposure.',
  },
  '冬至': {
    name: 'Winter Solstice(Dong Zhi)',
    intro: 'Winter Solstice usually falls around December 21-23. It is the shortest day and longest night of the year in the Northern Hemisphere.',
    meaning: 'Daylight reaches its minimum and yang begins to return',
    climate: 'Severe cold begins, and the traditional nine cold periods start.',
    origin: 'It is one of the earliest established solar terms and became an important ritual day in ancient dynasties.',
    food: 'Dumplings and wontons in the north; tangyuan, rice balls, and winter wine in the south.',
    customs: 'Heaven and ancestor rites, eating dumplings or tangyuan, counting the nine cold periods, and gifting warm items.',
    health: 'Store energy, protect emerging yang, keep warm, and choose calm indoor exercise.',
  },
  '小寒': {
    name: 'Lesser Cold(Xiao Han)',
    intro: 'Lesser Cold usually falls around January 5-7. It marks the beginning of the coldest part of the year.',
    meaning: 'Cold strengthens and deep winter arrives',
    climate: 'Very cold weather, freezing conditions, and some of the lowest temperatures of the year.',
    origin: 'Classical calendars note that cold is still minor at first, while stronger cold follows later.',
    food: 'Mutton, beef, walnuts, dates, glutinous rice, vegetable rice, and Laba porridge.',
    customs: 'Viewing plum blossoms, ice games, preparing New Year goods, and eating Laba porridge.',
    health: 'Warm the body, nourish kidney energy, sleep early and rise later, and avoid raw cold foods.',
  },
  '大寒': {
    name: 'Greater Cold(Da Han)',
    intro: 'Greater Cold usually falls around January 20-21. It is the last solar term and a transition toward the coming spring.',
    meaning: 'Cold reaches its limit and spring approaches',
    climate: 'Freezing weather, snow, strong winds, and frequent temperature drops.',
    origin: 'After Greater Cold comes Chun Fen, so ancient people saw it as the turning point from winter storage to spring growth.',
    food: 'Glutinous rice in the south, cold-dispelling cakes in the north, and balanced foods that prepare the body for spring.',
    customs: 'Year-end offerings, dust cleaning, window pasting, market visits, and preparing for the New Year.',
    health: 'Keep out wind and cold, reduce heavy tonics gradually, and prepare for the rising energy of spring.',
  },
};
